apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dogs
  description: Dogs is an app that exposes dog breeds through an API
  links:
    - url: https://github.com/northlander/dogs
      title: GitHub Repo
      icon: github
  annotations:
    backstage.io/kubernetes-id: dogs
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=dogs'
    github.com/project-slug: northlander/dogs
    argocd/app-name: dogs
spec:
  type: service
  lifecycle: production
  owner: dogs-team
  system: pets
  providesApis:
    - dog-breeds